export const SURVEY_REQUEST = 'SURVEY_REQUEST'
export const SURVEY_SUCCESS = 'SURVEY_SUCCESS'
export const SURVEY_FAIL = 'SURVEY_FAIL'

export const SURVEY_SEND_ANSWERS_REQUEST = 'SURVEY_SEND_ANSWERS_REQUEST'
export const SURVEY_SEND_ANSWERS_SUCCESS = 'SURVEY_SEND_ANSWERS_SUCCESS'
export const SURVEY_SEND_ANSWERS_FAIL = 'SURVEY_SEND_ANSWERS_FAIL'