export const CHECK_IN_TIME_SLOT_REQUEST = 'CHECK_IN_TIME_SLOT_REQUEST'
export const CHECK_IN_TIME_SLOT_SUCCESS = 'CHECK_IN_TIME_SLOT_SUCCESS'
export const CHECK_IN_TIME_SLOT_FAIL = 'CHECK_IN_TIME_SLOT_FAIL'
